name: "Demo_history_graph
version: "1.0.0"
slug: "sleeppad_0x85"
description: "Addon to read Sleeppad sensor data and post to Home Assistant"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: manual

options:
  api_base_url:
    description: "Base URL of Home Assistant API"
    type: str
    required: true
    example: "http://192.168.239.242:8123/api"
  api_token:
    description: "Long-Lived Access Token for Home Assistant API"
    type: str
    required: true
    example: "your_ll_token"
schema:
  api_base_url: str
  api_token: str